spring:
  application:
    name: embedding-similarity-sample
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
server:
  port: 9302
logging:
  level:
    org.springframework.ai: DEBUG
